### ISSUE TITLE
WIX build problem

### ISSUE THREAD

**Issue by mdblack98** [ramdor/Thetis-2.9.0#50] opened 2022-06-08 17:25 UTC
Download fresh git repo.
Open Thetis_VS2022.sln
Thetis installer upgrade fails (all other upgrades are OK)
Thetis-Installer\Thetis-Installer.wixproj: The application which this project type is based on was not found. Please try this link for further information: 930c7802-8a8c-48f9-8165-68863bccd9dd
I do have the latest build.386 4.0 WIX toolset installed
But can't quite figure out how to do the dotnet command to try and fix this.
 dotnet add PROJECT package WixToolset.UI.wixext --version 4.0.0-preview.1-build.384

**Comment by ramdor** [comment] 2023-01-06 15:21
x64 setup built fine for me.  You have to add WiX v3 visual studio 2022 extension. You can do this through the Manage Extensions from the Extensions menu on the top bar.

I already had old version obviously on here from 2022, but I did need to install a WiX update, which happens on shutdown. First time I tried it failed (just sat there on installer window), so cancelled that. Then started up VS2022 again tried again and it worked. Not sure what happened, but it is building ok here.

I will close this as not a bug.

```
7>		Thetis-Installer -> C:\Users\Richie\Documents\Coding\Thetis-2.9.0\Project Files\bin\Installers\Thetis.msi
========== Build: 7 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Elapsed 00:17.298 ==========
```

**Closed by ramdor** 2023-01-06 15:21 UTC
Labels: bug
