### ISSUE TITLE
Convert AmpView display to DirectX [FEATURE]

### ISSUE THREAD

**Issue by w-u-2-o** [ramdor/Thetis-2.9.0#114] opened 2023-05-12 14:42 UTC
**Is your feature request related to a problem? Please describe.**

The way the AmpView display is coded, it is a drain on resources and, even in "low res" mode, can cause glitches in VAC audio performance necessitating larger VAC ringbuffer settings. I.e. VAC settings can be optimized for low latency, but then turn out to be too aggressive and require relaxation when the AmpView display is running.

Given the important of the AmpView display, anything that can improve its performance would be well appreciated.

**Describe the solution you'd like**

Recode AmpView to use DirectX.

**Comment by mdblack98** [comment] 2023-05-12 15:14
There are two fairly large loops in the display routine.  Perhaps putting a Thread.Yield() inside the loop every ((n % X)==0) iterations would help. Maybe every 10 iterations.

**Comment by mdblack98** [comment] 2023-05-12 15:15
Also adding all the points at once rather than per point would probably help reduce the CPU load.

**Comment by ramdor** [comment] 2023-05-29 18:58
fwiw the ampview form is entirely run on its own thread in a single threaded apartment (STA), with its own message pump. You can add `while(true);` in the timer1_Tick event and the rest of Thetis will be fine. I wonder if it is more to do with the GetPSDisp call. Needs investigation.

**Comment by ramdor** [comment] 2023-05-29 22:06
GetPSDisp was a red herring. The issue is caused by endlessly adding/removing potentially thousands and thousands of points to the chart 10 times a second. I have now re-coded this, so the points are added once, then adjusted. I will be in contact @w-u-2-o  with an exe to test at some point over the next couple of days.

**Comment by w-u-2-o** [comment] 2023-05-29 22:17
Great find, Richie! Standing by to support.

**Comment by ramdor** [comment] 2023-06-12 01:32
updating positions instead of deleting/creating has improved things in 2.9.0.8. Closing.

**Closed by ramdor** 2023-06-12 01:32 UTC
Labels: enhancement
